'use client';
import {useState} from 'react';
import {ArrowUpRight, ArrowRight, Menu, X} from 'lucide-react';
import {motion} from 'framer-motion';
import {services,projects,plannerOptions} from '@/lib/data';

const Logo=()=> <img className="brandLogo" src="/bliss-logo.svg" alt="Bliss Crafted" />;

export default function Home(){
 const [menu,setMenu]=useState(false); const [selected,setSelected]=useState('signature');
 const chosen=plannerOptions.find(x=>x.value===selected)!;
 return <div>
  <header className="nav"><a className="brand" href="#top"><Logo/></a><nav className="navlinks">{['Story','Services','Work','Planner','Contact'].map(x=><a key={x} href={'#'+x.toLowerCase()}>{x}</a>)}</nav><button className="md:hidden" onClick={()=>setMenu(!menu)} aria-label="Menu">{menu?<X/>:<Menu/>}</button>{menu&&<div className="absolute top-full left-0 right-0 bg-[#11110f] text-white p-7 flex flex-col gap-5 md:hidden">{['Story','Services','Work','Planner','Contact'].map(x=><a key={x} href={'#'+x.toLowerCase()} onClick={()=>setMenu(false)}>{x}</a>)}</div>}</header>
  <main id="top">
   <section className="hero"><div className="heroMedia"/><div className="heroContent"><p className="eyebrow">EVENT DESIGN · PRODUCTION · EXPERIENCES</p><h1>Moments<br/>worth <em>feeling.</em></h1><p>We craft celebrations with a point of view — intimate, immersive and unmistakably yours.</p><a className="heroCta" href="#planner">Begin your story <ArrowUpRight size={17}/></a></div><div className="heroMeta">INDIA · WORLDWIDE</div></section>
   <section className="statement" id="story"><p className="eyebrow">A DIFFERENT KIND OF EVENT COMPANY</p><h2 className="headline">We turn <em>ideas</em> into<br/>atmospheres.</h2><div className="statementCopy">Bliss Crafted brings creative direction, meticulous planning and production together under one roof. No templates. No ordinary. Just thoughtfully made experiences that stay with people.<br/><a href="#services">Discover our approach <ArrowRight size={14}/></a></div></section>
   <section id="services"><div className="sectionTop"><div><p className="eyebrow">02 — WHAT WE CREATE</p><h2 className="headline">From first thought<br/>to <em>final toast.</em></h2></div><p>CURATED · PERSONAL · TIMELESS</p></div><div className="servicesGrid">{services.map(s=><motion.article whileHover={{x:8}} className="serviceRow" key={s.no}><span className="serviceNo">{s.no}</span><div><h3>{s.title}</h3><p>{s.description}</p></div><b>↗</b></motion.article>)}</div></section>
   <section className="method"><div className="methodImage"/><div className="methodCopy"><p className="eyebrow">THE BLISS CRAFTED METHOD</p><h2>Less formula.<br/><em>More feeling.</em></h2><p>Every event starts with listening. Then comes the concept, the visual language, the details and the choreography that makes everything feel effortless.</p><div className="steps">{['Listen','Imagine','Craft','Celebrate'].map((x,i)=><div key={x}><strong>0{i+1}</strong><span>{x}</span></div>)}</div></div></section>
   <section className="portfolio" id="work"><div className="sectionTop"><div><p className="eyebrow">03 — EXPERIENCES</p><h2 className="headline">A few things<br/>we've <em>crafted.</em></h2></div><p>SWIPE · SCROLL · WANDER</p></div><div className="portfolioRail">{projects.map((p,i)=><motion.article whileHover={{scale:.985}} key={p.title} className={'project p'+(i+1)} style={{backgroundImage:`url(${p.image})`}}><div className="projectContent"><small>{p.type}</small><h3>{p.title}</h3></div></motion.article>)}</div></section>
   <section className="planner" id="planner"><p className="eyebrow">04 — QUICK EVENT PLANNER</p><div className="plannerCard"><div><h2>Start with a <em>feeling.</em></h2><p>Choose a starting scale below. This is dummy pricing for now; later we’ll connect it to your real packages, add-ons and quotation engine.</p><strong className="text-3xl font-serif">₹{chosen.price.toLocaleString('en-IN')}+</strong><p>{chosen.detail}</p></div><div className="plannerChoices">{plannerOptions.map(o=><button className={'choice '+(selected===o.value?'active':'')} key={o.value} onClick={()=>setSelected(o.value)}><span>{o.label}</span><span className="price">₹{o.price.toLocaleString('en-IN')}+</span></button>)}<a className="heroCta !text-black !border-black mt-4" href="#contact">Build my event <ArrowUpRight size={17}/></a></div></div></section>
   <section className="contact" id="contact"><p className="eyebrow">05 — YOUR NEXT CHAPTER</p><h2 className="headline">Have a date?<br/>Let's make it <em>extraordinary.</em></h2><a className="contactLink" href="mailto:hello@blisscrafted.in">hello@blisscrafted.in&nbsp; ↗</a><p className="contactNote">Dummy contact for now — we’ll replace this with your real business details.</p></section>
  </main><footer><div className="brand"><Logo/></div><p>Celebrate Beyond Expectation.</p><nav><a href="#story">Story</a><a href="#services">Services</a><a href="#work">Work</a><a href="#contact">Contact</a></nav><small>© {new Date().getFullYear()} Bliss Crafted · Prototype</small></footer>
 </div>
}