'use client';
import {useState} from 'react';
import Link from 'next/link';
import {ArrowRight,ArrowUpRight,Menu,X,Check,ChevronDown} from 'lucide-react';
import {motion} from 'framer-motion';
import {services,projects,plannerOptions,dummyTestimonials,faqs} from '@/lib/data';

const Logo=()=> <img className="brandLogo" src="/bliss-logo.svg" alt="Bliss Crafted" />;

export default function Home(){
 const [menu,setMenu]=useState(false); const [selected,setSelected]=useState('signature'); const [openFaq,setOpenFaq]=useState<number|null>(null);
 const chosen=plannerOptions.find(x=>x.value===selected)!;
 return <div>
  <header className="nav"><Link className="brand" href="#top"><Logo/></Link><nav className="navlinks">{['Story','Services','Work','Planner','Contact'].map(x=><a key={x} href={'#'+x.toLowerCase()}>{x}</a>)}<Link href="/events">Experiences</Link></nav><div className="navActions"><Link className="navLogin" href="/login">Client login</Link><button className="menuBtn" onClick={()=>setMenu(!menu)} aria-label="Menu">{menu?<X size={20}/>:<Menu size={20}/>}</button></div>{menu&&<div className="mobileMenu">{['Story','Services','Work','Planner','Contact'].map(x=><a key={x} href={'#'+x.toLowerCase()} onClick={()=>setMenu(false)}>{x}</a>)}<Link href="/events" onClick={()=>setMenu(false)}>Experiences</Link><Link href="/login" onClick={()=>setMenu(false)}>Client login</Link></div>}</header>
  <main id="top">
   <section className="hero"><div className="heroMedia"/><div className="heroOverlay"/><div className="heroContent"><p className="eyebrow">EVENT DESIGN · PRODUCTION · EXPERIENCES</p><h1>Moments<br/>worth <em>feeling.</em></h1><p>We craft celebrations with a point of view — intimate, immersive and unmistakably yours.</p><div className="heroButtons"><a className="heroCta" href="#planner">Begin your story <ArrowUpRight size={17}/></a><Link className="ghostCta" href="/events">Explore experiences <ArrowRight size={16}/></Link></div></div><div className="heroMeta">INDIA · WORLDWIDE</div><div className="scrollCue">SCROLL <span>↓</span></div></section>
   <section className="statement" id="story"><p className="eyebrow">01 — A DIFFERENT KIND OF EVENT COMPANY</p><h2 className="headline">We turn <em>ideas</em> into<br/>atmospheres.</h2><div className="statementCopy"><p>Bliss Crafted brings creative direction, meticulous planning and production together under one roof. No templates. No ordinary. Just thoughtfully made experiences that stay with people.</p><a href="#services">Discover our approach <ArrowRight size={14}/></a></div></section>
   <section id="services"><div className="sectionTop"><div><p className="eyebrow">02 — WHAT WE CREATE</p><h2 className="headline">From first thought<br/>to <em>final toast.</em></h2></div><p>CURATED · PERSONAL · TIMELESS</p></div><div className="servicesGrid">{services.map(s=><motion.article whileHover={{x:8}} className="serviceRow" key={s.no}><span className="serviceNo">{s.no}</span><div><h3>{s.title}</h3><p>{s.description}</p><div className="serviceDetails">{s.details.map(d=><span key={d}>{d}</span>)}</div></div><b>↗</b></motion.article>)}</div></section>
   <section className="method"><div className="methodImage"/><div className="methodCopy"><p className="eyebrow">THE BLISS CRAFTED METHOD</p><h2>Less formula.<br/><em>More feeling.</em></h2><p>Every event starts with listening. Then comes the concept, the visual language, the details and the choreography that makes everything feel effortless.</p><div className="steps">{['Listen','Imagine','Craft','Celebrate'].map((x,i)=><div key={x}><strong>0{i+1}</strong><span>{x}</span></div>)}</div></div></section>
   <section className="portfolio" id="work"><div className="sectionTop"><div><p className="eyebrow">03 — EXPERIENCES</p><h2 className="headline">A few things<br/>we've <em>crafted.</em></h2></div><Link href="/events" className="sectionLink">View all experiences <ArrowUpRight size={15}/></Link></div><div className="portfolioRail">{projects.map((p,i)=><motion.article whileHover={{scale:.985}} key={p.title} className={'project p'+(i+1)} style={{backgroundImage:`url(${p.image})`}}><div className="projectContent"><small>{p.type}</small><h3>{p.title}</h3></div></motion.article>)}</div></section>
   <section className="planner" id="planner"><p className="eyebrow">04 — QUICK EVENT PLANNER</p><div className="plannerCard"><div><h2>Start with a <em>feeling.</em></h2><p>Choose a starting scale. This prototype gives you an indicative starting point; your final proposal is always bespoke.</p><div className="estimate"><span>ESTIMATED START</span><strong>₹{chosen.price.toLocaleString('en-IN')}+</strong><small>{chosen.detail}</small></div><div className="includes"><span>Includes</span>{chosen.includes.map(x=><div key={x}><Check size={14}/>{x}</div>)}</div></div><div className="plannerChoices">{plannerOptions.map(o=><button className={'choice '+(selected===o.value?'active':'')} key={o.value} onClick={()=>setSelected(o.value)}><span>{o.label}</span><span className="price">₹{o.price.toLocaleString('en-IN')}+</span></button>)}<Link className="darkButton" href="/planner">Build my event <ArrowUpRight size={17}/></Link></div></div></section>
   <section className="testimonials"><div className="sectionTop"><div><p className="eyebrow">05 — WORDS FROM THE OTHER SIDE</p><h2 className="headline">Good events<br/>leave <em>echoes.</em></h2></div></div><div className="testimonialGrid">{dummyTestimonials.map(t=><article key={t.name}><span>“</span><p>{t.quote}</p><footer><strong>{t.name}</strong><small>{t.type}</small></footer></article>)}</div></section>
   <section className="faq"><div><p className="eyebrow">06 — QUESTIONS, ANSWERED</p><h2 className="headline">Before we<br/><em>begin.</em></h2></div><div className="faqList">{faqs.map(([q,a],i)=><div className={'faqItem '+(openFaq===i?'open':'')} key={q}><button onClick={()=>setOpenFaq(openFaq===i?null:i)}><span>{q}</span><ChevronDown size={17}/></button>{openFaq===i&&<p>{a}</p>}</div>)}</div></section>
   <section className="contact" id="contact"><p className="eyebrow">07 — YOUR NEXT CHAPTER</p><h2 className="headline">Have a date?<br/>Let's make it <em>extraordinary.</em></h2><div className="contactRow"><div><a className="contactLink" href="mailto:hello@blisscrafted.in">hello@blisscrafted.in&nbsp; ↗</a><p className="contactNote">Prototype contact — replace with your final business details.</p></div><Link className="darkButton" href="/planner">Start planning <ArrowUpRight size={17}/></Link></div></section>
  </main><footer className="siteFooter"><div className="footerTop"><div><div className="brand"><Logo/></div><p>Celebrate Beyond Expectation.</p></div><nav><Link href="/">Home</Link><Link href="/events">Experiences</Link><Link href="/planner">Planner</Link><Link href="/login">Client login</Link></nav><div className="footerSocial"><span>Instagram</span><span>WhatsApp</span></div></div><div className="footerBottom"><small>© {new Date().getFullYear()} Bliss Crafted</small><small>India · Worldwide</small><div><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div></div></footer>
 </div>
}
